title: Ahin Lee
email: ahin@unist.ac.kr
description: >-
  One-page personal site for Ahin Lee built with GitHub Pages and Jekyll.
baseurl: ""
url: "https://ahin-page.github.io"
lang: en
timezone: Asia/Seoul
markdown: kramdown
plugins:
  - jekyll-seo-tag
